package me.kpavlov.ksp.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugin.descriptor.PluginDescriptor;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/**
 * Abstract base class for KSP (Kotlin Symbol Processing) Maven plugin mojos.
 *
 * <p>This class provides the common configuration parameters for KSP processing,
 * including source directories, output directories, and processing options.
 * Subclasses implement scope-specific behavior for main and test sources.</p>
 *
 * <h2>Thread Safety</h2>
 * <p>This mojo is thread-safe and supports parallel Maven builds. Each execution creates
 * isolated KSP processing instances with no shared mutable state.</p>
 *
 * <h2>Configuration</h2>
 * <p>Most parameters have sensible defaults and can be configured via the plugin
 * configuration in {@code pom.xml} or via system properties.</p>
 *
 * @author Konstantin Pavlov
 * @since 0.1.0
 */
public abstract class AbstractKspProcessMojo extends AbstractMojo implements KspMojoParameters {

    /**
     * Plugin descriptor for accessing plugin artifacts.
     */
    @Parameter(defaultValue = "${plugin}", readonly = true)
    private PluginDescriptor pluginDescriptor;

    /**
     * The Maven project being built.
     */
    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /**
     * Source directory to process.
     *
     * <p>If not specified, defaults to the standard source directory for the scope
     * (main or test). For main sources, typically {@code src/main/kotlin}.</p>
     *
     * @since 0.1.0
     */
    @Parameter
    private File sourceDirectory;

    /**
     * Additional source directories to include in processing.
     *
     * <p>These directories are added to the Java source roots for KSP processing.</p>
     *
     * @since 0.1.0
     */
    @Parameter
    private List<File> sourceDirs;

    /**
     * Output directory for generated Kotlin sources.
     *
     * <p>If not specified, defaults to {@code target/generated-sources/ksp} for main sources
     * or {@code target/generated-test-sources/ksp} for test sources.</p>
     *
     * @since 0.1.0
     */
    @Parameter
    private File kotlinOutputDir;

    /**
     * Output directory for generated Java sources.
     *
     * <p>If not specified, defaults to the same directory as Kotlin output.</p>
     *
     * @since 0.1.0
     */
    @Parameter
    private File javaOutputDir;

    /**
     * Output directory for compiled classes generated by KSP.
     *
     * <p>If not specified, defaults to {@code target/ksp-classes} for main sources
     * or {@code target/ksp-test-classes} for test sources.</p>
     *
     * @since 0.1.0
     */
    @Parameter
    private File classOutputDir;

    /**
     * Output directory for generated resources.
     *
     * <p>If not specified, defaults to {@code target/generated-resources/ksp} for main sources
     * or {@code target/generated-test-resources/ksp} for test sources.</p>
     *
     * @since 0.1.0
     */
    @Parameter
    private File resourceOutputDir;

    /**
     * KSP output directory for internal KSP outputs.
     *
     * <p>If not specified, defaults to {@code target/ksp} for main sources
     * or {@code target/ksp-test} for test sources.</p>
     *
     * @since 0.1.0
     */
    @Parameter
    private File kspOutputDir;

    /**
     * Cache directory for incremental processing.
     *
     * <p>KSP uses this directory to cache incremental compilation data.</p>
     *
     * <p>If not specified, defaults to {@code target/ksp-cache} for main sources
     * or {@code target/ksp-test-cache} for test sources.</p>
     *
     * @since 0.1.0
     */
    @Parameter
    private File cachesDir;

    /**
     * Enable incremental processing.
     *
     * <p>When enabled, KSP will only process files that have changed since the last build.
     * This can significantly improve build times for large projects.</p>
     *
     * @since 0.1.0
     */
    @Parameter(defaultValue = "false")
    private boolean incremental;

    /**
     * Enable incremental processing log output.
     *
     * <p>When enabled, logs information about which files were modified, removed,
     * or had their classes changed during incremental processing.</p>
     *
     * @since 0.1.0
     */
    @Parameter(defaultValue = "false")
    private boolean incrementalLog;

    /**
     * JVM default mode for generating default interface methods.
     *
     * @since 0.1.0
     */
    @Parameter(property = "kotlin.compiler.jvmDefault", defaultValue = "")
    private String jvmDefaultMode = "";

    /**
     * Kotlin language version.
     *
     * <p>If not specified, the version is resolved from:</p>
     * <ol>
     *   <li>kotlin-maven-plugin configuration</li>
     *   <li>{@code kotlin.compiler.languageVersion} property</li>
     *   <li>{@code kotlin.version} property (major.minor)</li>
     *   <li>Default: 2.3</li>
     * </ol>
     *
     * @since 0.1.0
     */
    @Parameter(property = "kotlin.compiler.languageVersion", defaultValue = "2.3")
    private String languageVersion;

    /**
     * Kotlin API version.
     *
     * <p>If not specified, defaults to the same as {@link #languageVersion}.</p>
     *
     * @since 0.1.0
     */
    @Parameter(property = "kotlin.compiler.apiVersion")
    private String apiVersion;

    /**
     * Ignore processing errors during KSP execution.
     *
     * <p>When set to {@code true}, the processing will continue even if errors occur,
     * potentially generating incomplete or invalid outputs. If set to {@code false},
     * the execution will halt on encountering an error.</p>
     *
     * @since 0.1.0
     */
    @Parameter(defaultValue = "false")
    private boolean ignoreProcessingErrors;

    /**
     * Treat all Kotlin compiler warnings as errors.
     *
     * <p>This setting is resolved from multiple sources:</p>
     * <ol>
     *   <li>This parameter</li>
     *   <li>kotlin-maven-plugin configuration</li>
     *   <li>{@code kotlin.compiler.allWarningsAsErrors} property</li>
     * </ol>
     *
     * @since 0.1.0
     */
    @Parameter(property = "kotlin.compiler.allWarningsAsErrors", defaultValue = "false")
    private boolean allWarningsAsErrors;

    /**
     * Map annotation arguments in Java source files.
     *
     * <p>When enabled, KSP will process annotation arguments in Java source files.</p>
     *
     * @since 0.1.0
     */
    @Parameter(defaultValue = "true")
    private boolean mapAnnotationArgumentsInJava = true;

    /**
     * Enable debug output.
     *
     * <p>When enabled, additional diagnostic information is logged during KSP processing,
     * including configuration details, discovered processors, and incremental changes.</p>
     *
     * @since 0.1.0
     */
    @Parameter(property = "ksp.debug", defaultValue = "false")
    private boolean debug;

    /**
     * Glob-style patterns of fully-qualified SymbolProcessorProvider class names to include.
     *
     * <p>When empty, all discovered processors are included by default.
     * Use {@code *} to match within a single package segment and {@code **} to match across segments.</p>
     *
     * <p>Example: include only processors from a specific package:</p>
     * <pre>{@code
     * <processorIncludes>
     *   <processorInclude>com.example.annotation.*</processorInclude>
     * </processorIncludes>
     * }</pre>
     *
     * @since 0.4.0
     */
    @Parameter
    private List<String> processorIncludes;

    /**
     * Glob-style patterns of fully-qualified SymbolProcessorProvider class names to exclude.
     *
     * <p>Providers matching any exclude pattern are removed even if they satisfy an include pattern.</p>
     *
     * <p>Example: exclude a specific processor:</p>
     * <pre>{@code
     * <processorExcludes>
     *   <processorExclude>com.example.SlowProcessor</processorExclude>
     * </processorExcludes>
     * }</pre>
     *
     * @since 0.4.0
     */
    @Parameter
    private List<String> processorExcludes;

    /**
     * KSP processor options (key-value pairs).
     *
     * <p>These options are passed to KSP processors and can be accessed via
     * {@code SymbolProcessorEnvironment.options}.</p>
     *
     * <p>Example:</p>
     * <pre>{@code
     * <processorOptions>
     *   <option1>value1</option1>
     *   <option2>value2</option2>
     * </processorOptions>
     * }</pre>
     *
     * @since 0.1.0
     */
    @Parameter
    private Map<String, String> processorOptions;

    /**
     * Module name for KSP processing.
     *
     * <p>If not specified, defaults to the project's artifact ID.</p>
     *
     * @since 0.1.0
     */
    @Parameter(defaultValue = "${project.artifactId}")
    private String moduleName;

    /**
     * JVM target version for code generation.
     *
     * <p>If not specified, the version is resolved from:</p>
     * <ol>
     *   <li>kotlin-maven-plugin configuration</li>
     *   <li>{@code kotlin.compiler.jvmTarget} property</li>
     *   <li>{@code maven.compiler.release} property</li>
     *   <li>{@code maven.compiler.target} property</li>
     *   <li>Default: 11</li>
     * </ol>
     *
     * @since 0.1.0
     */
    @Parameter(property = "kotlin.compiler.jvmTarget", defaultValue = "11")
    private String jvmTarget;

    /**
     * Add generated sources to compilation.
     *
     * <p>When enabled, generated Kotlin and Java sources are automatically added
     * to the compile source roots, and generated resources are added to the project resources.</p>
     *
     * @since 0.1.0
     */
    @Parameter(defaultValue = "true")
    private boolean addGeneratedSourcesToCompile = true;

    /**
     * Returns the processing scope (MAIN or TEST).
     *
     * @return the processing scope for this mojo
     */
    @Override
    public abstract ProcessingScope getScope();

    /**
     * Returns whether processing should be skipped.
     *
     * @return {@code true} if processing should be skipped
     */
    protected abstract boolean isSkip();

    /**
     * Factory for creating KSP instances. Can be overridden for testing.
     *
     * @return the KSP factory
     */
    @Override
    public KspFactory getKspFactory() {
        return DefaultKspFactory.INSTANCE;
    }

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        if (isSkip()) {
            getLog().info("Skipping KSP processing (" + getScope() + " scope)");
            return;
        }

        KspMojoExecutors.execute(this);
    }

    // ── KspMojoParameters getters ─────────────────────────────────────────────

    @Override
    public MavenProject getProject() {
        return project;
    }

    @Override
    public PluginDescriptor getPluginDescriptor() {
        return pluginDescriptor;
    }

    @Override
    public File getSourceDirectory() {
        return sourceDirectory;
    }

    @Override
    public List<File> getSourceDirs() {
        return sourceDirs != null ? sourceDirs : Collections.emptyList();
    }

    @Override
    public File getKotlinOutputDir() {
        return kotlinOutputDir;
    }

    @Override
    public File getJavaOutputDir() {
        return javaOutputDir;
    }

    @Override
    public File getClassOutputDir() {
        return classOutputDir;
    }

    @Override
    public File getResourceOutputDir() {
        return resourceOutputDir;
    }

    @Override
    public File getKspOutputDir() {
        return kspOutputDir;
    }

    @Override
    public File getCachesDir() {
        return cachesDir;
    }

    @Override
    public boolean getIncremental() {
        return incremental;
    }

    @Override
    public boolean getIncrementalLog() {
        return incrementalLog;
    }

    @Override
    public String getJvmDefaultMode() {
        return jvmDefaultMode;
    }

    @Override
    public String getLanguageVersion() {
        return languageVersion;
    }

    @Override
    public String getApiVersion() {
        return apiVersion;
    }

    @Override
    public boolean getIgnoreProcessingErrors() {
        return ignoreProcessingErrors;
    }

    @Override
    public boolean getAllWarningsAsErrors() {
        return allWarningsAsErrors;
    }

    @Override
    public boolean getMapAnnotationArgumentsInJava() {
        return mapAnnotationArgumentsInJava;
    }

    @Override
    public boolean getDebug() {
        return debug;
    }

    @Override
    public List<String> getProcessorIncludes() {
        return processorIncludes != null ? processorIncludes : Collections.emptyList();
    }

    @Override
    public List<String> getProcessorExcludes() {
        return processorExcludes != null ? processorExcludes : Collections.emptyList();
    }

    @Override
    public Map<String, String> getProcessorOptions() {
        return processorOptions != null ? processorOptions : Collections.emptyMap();
    }

    @Override
    public String getModuleName() {
        return moduleName;
    }

    @Override
    public String getJvmTarget() {
        return jvmTarget;
    }

    @Override
    public boolean getAddGeneratedSourcesToCompile() {
        return addGeneratedSourcesToCompile;
    }
}
