package me.kpavlov.ksp.maven

import org.apache.maven.plugin.descriptor.PluginDescriptor
import org.apache.maven.plugin.logging.Log
import org.apache.maven.project.MavenProject
import java.io.File

/**
 * Parameters contract for KSP Mojo execution.
 *
 * This interface is implemented by Java Mojos (which hold the Maven parameter
 * annotations and Javadoc for the maven-plugin-plugin to extract documentation)
 * and consumed by [KspMojoExecutors] to run KSP processing.
 *
 * Default implementations of the `getActual*` helpers (e.g. [getActualSourceDirectory])
 * resolve each optional directory to its scope-specific default when the caller has not
 * set an explicit value. These defaults are proper Java 8 interface default methods
 * (requires `-jvm-default=enable`), so Java implementors inherit them automatically.
 */
interface KspMojoParameters {
    /** The Maven project being built. */
    val project: MavenProject

    /** Plugin descriptor for accessing plugin artifacts. */
    val pluginDescriptor: PluginDescriptor?

    /** Maven logger. */
    val log: Log

    /** Processing scope (MAIN or TEST). */
    val scope: ProcessingScope

    /** Factory for creating KSP instances. */
    val kspFactory: KspFactory

    /** Explicit source directory; defaults to the scope's standard source directory when null. */
    val sourceDirectory: File?

    /**
     * Additional source directories added to the Java source roots for KSP processing.
     * Never null; an empty list means no additional directories.
     */
    val sourceDirs: List<File>

    /** Output directory for generated Kotlin sources, or null to use the scope default. */
    val kotlinOutputDir: File?

    /** Output directory for generated Java sources, or null to use the scope default. */
    val javaOutputDir: File?

    /** Output directory for compiled classes generated by KSP, or null to use the scope default. */
    val classOutputDir: File?

    /** Output directory for generated resources, or null to use the scope default. */
    val resourceOutputDir: File?

    /** KSP internal output directory, or null to use the scope default. */
    val kspOutputDir: File?

    /** Cache directory for incremental processing, or null to use the scope default. */
    val cachesDir: File?

    /** Enable incremental processing. */
    val incremental: Boolean

    /** Enable incremental processing log output. */
    val incrementalLog: Boolean

    /**
     * JVM default mode for generating default interface methods in Kotlin interfaces.
     *
     * Allowed values (passed as `-jvm-default=<value>` to the Kotlin compiler):
     * - `enable` (default since Kotlin 2.2): generates default methods and `DefaultImpls`
     *            bridges for binary compatibility.
     * - `no-compatibility`: generates only default methods, skipping compatibility bridges.
     * - `disable`: disables default method generation; only `DefaultImpls` classes are produced.
     */
    val jvmDefaultMode: String

    /** Kotlin language version, or null to resolve from the project. */
    val languageVersion: String?

    /** Kotlin API version, or null to default to [languageVersion]. */
    val apiVersion: String?

    /** When true, build continues even if KSP processing reports errors. */
    val ignoreProcessingErrors: Boolean

    /** Treat all Kotlin compiler warnings as errors. */
    val allWarningsAsErrors: Boolean

    /** Map annotation arguments in Java source files. */
    val mapAnnotationArgumentsInJava: Boolean

    /** Enable debug output. */
    val debug: Boolean

    /** Glob-style patterns for processor class names to include; empty means include all. */
    val processorIncludes: List<String>

    /** Glob-style patterns for processor class names to exclude. */
    val processorExcludes: List<String>

    /**
     * KSP processor options (key-value pairs) passed to processors via
     * [com.google.devtools.ksp.processing.SymbolProcessorEnvironment.options].
     */
    val processorOptions: Map<String, String>

    /** Module name for KSP processing. */
    val moduleName: String

    /** JVM target version, or null to resolve from the project. */
    val jvmTarget: String?

    /** When true, generated Kotlin/Java sources and resources are added to the compile roots. */
    val addGeneratedSourcesToCompile: Boolean

    // ── Computed directory accessors ─────────────────────────────────────────

    /** Returns the resolved source directory, falling back to the scope default. */
    fun getActualSourceDirectory(): File = sourceDirectory ?: scope.getSourceDirectory(project)

    /** Returns the resolved Kotlin output directory, falling back to the scope default. */
    fun getActualKotlinOutputDir(): File =
        kotlinOutputDir ?: scope.getDefaultKotlinOutputDir(project.build.directory)

    /** Returns the resolved Java output directory, falling back to the scope default. */
    fun getActualJavaOutputDir(): File =
        javaOutputDir ?: scope.getDefaultJavaOutputDir(project.build.directory)

    /** Returns the resolved class output directory, falling back to the scope default. */
    fun getActualClassOutputDir(): File =
        classOutputDir ?: scope.getDefaultClassOutputDir(project.build.directory)

    /** Returns the resolved resource output directory, falling back to the scope default. */
    fun getActualResourceOutputDir(): File =
        resourceOutputDir ?: scope.getDefaultResourceOutputDir(project.build.directory)

    /** Returns the resolved KSP output directory, falling back to the scope default. */
    fun getActualKspOutputDir(): File =
        kspOutputDir ?: scope.getDefaultKspOutputDir(project.build.directory)

    /** Returns the resolved caches directory, falling back to the scope default. */
    fun getActualCachesDir(): File = cachesDir ?: scope.getDefaultCachesDir(project.build.directory)
}
