package me.kpavlov.ksp.maven.testprocessor

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated

/**
 * Generates a Kotlin file containing invalid syntax, causing a compilation failure.
 *
 * This processor must never run in a real build. It exists solely as a canary:
 * the sample project excludes [BreakingProcessorProvider] via `<processorExcludes>`,
 * and if that exclusion ever stops working this processor will fire, the generated
 * file will fail to compile, and the build will break — surfacing the regression.
 */
class BreakingProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {
    override fun process(resolver: Resolver): List<KSAnnotated> {
        logger.error("BreakingProcessor is running — this processor should have been excluded!")

        codeGenerator
            .createNewFile(
                dependencies = Dependencies.ALL_FILES,
                packageName = "broken",
                fileName = "BrokenCode",
            ).bufferedWriter()
            .use { writer ->
                writer.write(
                    """
                    // THIS FILE IS INTENTIONALLY INVALID.
                    // BreakingProcessor was not excluded — processorExcludes filtering is broken.
                    THIS IS NOT VALID KOTLIN SYNTAX AND WILL NOT COMPILE
                    Generated by ${BreakingProcessor::class.qualifiedName}.
                    """.trimIndent(),
                )
            }

        return emptyList()
    }
}
